# Generated by Django 4.2.3 on 2023-07-25 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("signup_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="career",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
